import numpy
import torch
from .pdb_parsing import parse_pdb

ordered_canonical_aa_types = (
    "ALA",
    "CYS",
    "ASP",
    "GLU",
    "PHE",
    "GLY",
    "HIS",
    "ILE",
    "LYS",
    "LEU",
    "MET",
    "ASN",
    "PRO",
    "GLN",
    "ARG",
    "SER",
    "THR",
    "VAL",
    "TRP",
    "TYR",
)

ordered_canonical_aa_atoms = {
    "ALA": (
        "N",
        "CA",
        "C",
        "O",
        "OXT",
        "CB",
        "H",
        "H1",
        "H2",
        "H3",
        "HA",
        "HB1",
        "HB2",
        "HB3",
    ),
    "CYS": (
        "N",
        "CA",
        "C",
        "O",
        "OXT",
        "CB",
        "SG",
        "H",
        "H1",
        "H2",
        "H3",
        "HA",
        "HB2",
        "HB3",
        "HG",
    ),
    "ASP": (
        "N",
        "CA",
        "C",
        "O",
        "OXT",
        "CB",
        "CG",
        "OD1",
        "OD2",
        "H",
        "H1",
        "H2",
        "H3",
        "HA",
        "HB2",
        "HB3",
    ),
    "GLU": (
        "N",
        "CA",
        "C",
        "O",
        "OXT",
        "CB",
        "CG",
        "CD",
        "OE1",
        "OE2",
        "H",
        "H1",
        "H2",
        "H3",
        "HA",
        "HB2",
        "HB3",
        "HG2",
        "HG2",
    ),
    "PHE": (
        "N",
        "CA",
        "C",
        "O",
        "OXT",
        "CB",
        "CG",
        "CD1",
        "CD2",
        "CE1",
        "CE2",
        "CZ",
        "H",
        "H1",
        "H2",
        "H3",
        "HA",
        "HB2",
        "HB3",
        "HD1",
        "HD2",
        "HE1",
        "HE2",
        "HZ",
    ),
    "GLY": ("N", "CA", "C", "O", "OXT", "H", "H1", "H2", "H3", "HA1", "HA2"),
    "HIS": (
        "N",
        "CA",
        "C",
        "O",
        "OXT",
        "CB",
        "CG",
        "ND1",
        "CD2",
        "CE1",
        "NE2",
        "NH",
        "NN",
        "H",
        "H1",
        "H2",
        "H3",
        "HA",
        "HB2",
        "HB3",
        "HD1",
        "HD2",
        "HE1",
        "HE2",
        "HN",
    ),
    "ILE": (
        "N",
        "CA",
        "C",
        "O",
        "OXT",
        "CB",
        "CG1",
        "CG2",
        "CD1",
        "H",
        "H1",
        "H2",
        "H3",
        "HA",
        "HB",
        "HG11",
        "HG12",
        "HG21",
        "HG22",
        "HG23",
        "HD11",
        "HD12",
        "HD13",
    ),
    "LYS": (
        "N",
        "CA",
        "C",
        "O",
        "OXT",
        "CB",
        "CG",
        "CD",
        "CE",
        "NZ",
        "H",
        "H1",
        "H2",
        "H3",
        "HA",
        "HB2",
        "HB3",
        "HG2",
        "HG3",
        "HD2",
        "HD3",
        "HE2",
        "HE3",
        "HZ1",
        "HZ2",
        "HZ3",
    ),
    "LEU": (
        "N",
        "CA",
        "C",
        "O",
        "OXT",
        "CB",
        "CG",
        "CD1",
        "CD2",
        "H",
        "H1",
        "H2",
        "H3",
        "HA",
        "HB2",
        "HB3",
        "HG",
        "HD11",
        "HD12",
        "HD13",
        "HD21",
        "HD22",
        "HD23",
    ),
    "MET": (
        "N",
        "CA",
        "C",
        "O",
        "OXT",
        "CB",
        "CG",
        "SD",
        "CE",
        "H",
        "H1",
        "H2",
        "H3",
        "HA",
        "HB2",
        "HB3",
        "HG2",
        "HG3",
        "HE1",
        "HE2",
        "HE3",
    ),
    "ASN": (
        "N",
        "CA",
        "C",
        "O",
        "OXT",
        "CB",
        "CG",
        "OD1",
        "OD2",
        "H",
        "H1",
        "H2",
        "H3",
        "HA",
        "HB2",
        "HB3",
        "HD21",
        "HD22",
    ),
    "PRO": (
        "N",
        "CA",
        "C",
        "O",
        "OXT",
        "CB",
        "CG",
        "CD",
        "H",
        "H1",
        "H2",
        "H3",
        "HA",
        "HB2",
        "HB3",
        "HG2",
        "HG3",
        "HD2",
        "HD3",
    ),
    "GLN": (
        "N",
        "CA",
        "C",
        "O",
        "OXT",
        "CB",
        "CG",
        "CD",
        "OE1",
        "OE2",
        "H",
        "H1",
        "H2",
        "H3",
        "HA",
        "HB2",
        "HB3",
        "HG2",
        "HG3",
        "HE21",
        "HE22",
    ),
    "ARG": (
        "N",
        "CA",
        "C",
        "O",
        "OXT",
        "CB",
        "CG",
        "CD",
        "NE",
        "CZ",
        "NH1",
        "NH2",
        "H",
        "H1",
        "H2",
        "H3",
        "HA",
        "HB2",
        "HB3",
        "HG2",
        "HG3",
        "HE",
        "HH11",
        "HH12",
        "HH13",
        "HH21",
        "HH22",
        "HH23",
    ),
    "SER": (
        "N",
        "CA",
        "C",
        "O",
        "OXT",
        "CB",
        "OG",
        "H",
        "H1",
        "H2",
        "H3",
        "HA",
        "HB2",
        "HB3",
        "HG",
    ),
    "THR": (
        "N",
        "CA",
        "C",
        "O",
        "OXT",
        "CB",
        "OG1",
        "CG2",
        "H",
        "H1",
        "H2",
        "H3",
        "HA",
        "HB2",
        "HB3",
        "HG1",
        "HG21",
        "HG22",
        "HG23",
    ),
    "VAL": (
        "N",
        "CA",
        "C",
        "O",
        "OXT",
        "CB",
        "CG1",
        "CG2",
        "H",
        "H1",
        "H2",
        "H3",
        "HA",
        "HB",
        "HG11",
        "HG12",
        "HG13",
        "HG21",
        "HG22",
        "HG23",
    ),
    "TRP": (
        "N",
        "CA",
        "C",
        "O",
        "OXT",
        "CB",
        "CG",
        "CD1",
        "CD2",
        "NE1",
        "CE2",
        "CE3",
        "CZ2",
        "CZ3",
        "CH2",
        "H",
        "H1",
        "H2",
        "H3",
        "HA",
        "HB2",
        "HB3",
        "HD1",
        "HE1",
        "HE3",
        "HZ2",
        "HZ3",
        "HH2",
    ),
    "TYR": (
        "N",
        "CA",
        "C",
        "O",
        "OXT",
        "CB",
        "CG",
        "CD1",
        "CD2",
        "CE1",
        "CE2",
        "CZ",
        "OH",
        "H",
        "H1",
        "H2",
        "H3",
        "HA",
        "HB2",
        "HB3",
        "HD1",
        "HD2",
        "HE1",
        "HE2",
        "HH",
    ),
}

max_n_canonical_atoms = max(
    len(atlist) for _, atlist in ordered_canonical_aa_atoms.items()
)


def canonical_form_from_pdb_lines(pdb_lines):
    atom_records = parse_pdb(pdb_lines)
    uniq_res_ind = {}
    uniq_res_list = []
    count_uniq = -1
    for i, row in atom_records.iterrows():
        resid = (row["chain"], row["resi"], row["insert"])
        if resid not in uniq_res_ind:
            count_uniq += 1
            uniq_res_ind[resid] = count_uniq
            uniq_res_list.append(resid)
    n_res = len(uniq_res_list)

    chain_begin = numpy.zeros((1, n_res), dtype=numpy.int32)
    res_types = numpy.full((1, n_res), -2, dtype=numpy.int32)
    coords = numpy.full(
        (1, n_res, max_n_canonical_atoms, 3), numpy.NAN, dtype=numpy.float32
    )
    atom_is_present = numpy.zeros((1, n_res, max_n_canonical_atoms), dtype=numpy.int32)

    chains_seen = set([])
    for i, row in atom_records.iterrows():
        resid = (row["chain"], row["resi"], row["insert"])
        res_ind = uniq_res_ind[resid]
        if row["chaini"] not in chains_seen:
            chains_seen.add(row["chaini"])
            chain_begin[0, res_ind] = 1
        if res_types[0, res_ind] == -2:
            try:
                aa_ind = ordered_canonical_aa_types.index(row["resn"])
                res_types[0, res_ind] = aa_ind
            except:
                res_types[0, res_ind] = -1
        if res_types[0, res_ind] > 0:
            res_at_list = ordered_canonical_aa_atoms[row["resn"]]
            atname = row["atomn"].strip()
            try:
                atind = res_at_list.index(atname)
                atom_is_present[0, res_ind, atind] = 1
                coords[0, res_ind, atind, 0] = row["x"]
                coords[0, res_ind, atind, 1] = row["y"]
                coords[0, res_ind, atind, 2] = row["z"]
            except:
                pass

    return chain_begin, res_types, coords, atom_is_present
