import torch
import numpy
import toolz
import biotite
import biotite.structure
from dataclasses import dataclass
import logging

from tmol.types.functional import validate_args
from tmol.chemical.restypes import ResidueTypeSet
from tmol.database import ParameterDatabase
from tmol.io.canonical_form import CanonicalForm
from tmol.io.canonical_ordering import CanonicalOrdering
from tmol.io.pose_stack_deconstruction import canonical_form_from_pose_stack
from tmol.pose.packed_block_types import PackedBlockTypes
from tmol.pose.pose_stack import PoseStack

from tmol import beta2016_score_function

logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class BiotitePoseBuildContext:
    """Immutable context for canonical-form-based pose construction."""

    canonical_form: CanonicalForm
    canonical_ordering: CanonicalOrdering
    packed_block_types: PackedBlockTypes
    parameter_database: ParameterDatabase
    restype_set: ResidueTypeSet


@validate_args
def build_context_from_biotite(
    biotite_structure: biotite.structure.AtomArray | biotite.structure.AtomArrayStack,
    torch_device: torch.device,
    param_db: ParameterDatabase | None = None,
    strict_atom_types: bool = False,
) -> BiotitePoseBuildContext:
    """Build immutable construction context from a Biotite structure.

    Args:
        biotite_structure: Input AtomArray or AtomArrayStack.
        torch_device: Target torch device.
        param_db: Optional parameter database. When provided, canonical ordering,
            residue types, and packed block types are built from this database.
        strict_atom_types: Whether unknown ligand atom types should raise.

    Returns:
        BiotitePoseBuildContext containing canonical form, ordering,
        packed block types, parameter database, and residue type set.
    """
    if param_db is None:
        co = canonical_ordering_for_biotite()
        cf = canonical_form_from_biotite(biotite_structure, torch_device, co=co)
        pbt = packed_block_types_for_biotite(cf.coords.device)
        db = _paramdb_for_biotite()
        rts = _restype_set_for_biotite()
    else:
        db = param_db
        co, rts, pbt = _derived_types_for_param_db(db, torch_device)
        cf = canonical_form_from_biotite(biotite_structure, torch_device, co=co)
    return BiotitePoseBuildContext(
        canonical_form=cf,
        canonical_ordering=co,
        packed_block_types=pbt,
        parameter_database=db,
        restype_set=rts,
    )


@validate_args
def pose_stack_from_biotite(
    biotite_structure: biotite.structure.AtomArray | biotite.structure.AtomArrayStack,
    torch_device: torch.device,
    param_db: ParameterDatabase | None = None,
    strict_atom_types: bool = False,
    return_context: bool = False,
    **kwargs: object,
) -> PoseStack | tuple[PoseStack, BiotitePoseBuildContext]:
    """Build a PoseStack from the output generated by Biotite.

    Args:
        biotite_structure: A Biotite AtomArray or AtomArrayStack.
        torch_device: Target PyTorch device.
        param_db: Optional ParameterDatabase. When provided, conversion and pose
            construction use this database.
        strict_atom_types: If True, unknown ligand atom types raise errors
            instead of using a fallback element heuristic.
        return_context: If True, return `(pose_stack, context)` where context
            contains canonical form, canonical ordering, parameter DB and PBT.
        **kwargs: Additional arguments passed to pose_stack_from_canonical_form.

    Returns:
        PoseStack when ``return_context`` is False, otherwise a tuple of
        ``(pose_stack, BiotitePoseBuildContext)``.
    """
    from tmol.io.pose_stack_construction import pose_stack_from_canonical_form
    from tmol.pack.build_missing_sidechains import (
        build_missing_sidechains_with_missing_atoms,
        create_dunbrack_sampler_from_database,
    )

    context = build_context_from_biotite(
        biotite_structure,
        torch_device,
        param_db=param_db,
        strict_atom_types=strict_atom_types,
    )

    result = pose_stack_from_canonical_form(
        context.canonical_ordering,
        context.packed_block_types,
        *context.canonical_form,
        return_block_has_missing_atoms=True,
        **kwargs,
    )

    if isinstance(result, tuple):
        pose_stack = result[0]
        block_has_missing_atoms = result[-1]
    else:
        pose_stack = result
        block_has_missing_atoms = None

    if block_has_missing_atoms is not None and torch.any(block_has_missing_atoms):
        db = context.parameter_database

        sfxn = beta2016_score_function(torch_device, param_db=db)
        dunbrack_sampler = create_dunbrack_sampler_from_database(db, torch_device)

        logger.info(
            "%i missing sidechains", torch.count_nonzero(block_has_missing_atoms)
        )
        pose_stack = build_missing_sidechains_with_missing_atoms(
            pose_stack,
            sfxn,
            dunbrack_sampler,
            block_has_missing_atoms,
            context.restype_set,
        )

    if return_context:
        return pose_stack, context
    return pose_stack


@validate_args
def biotite_from_pose_stack(
    pose_stack: PoseStack,
    co: CanonicalOrdering | None = None,
) -> biotite.structure.AtomArray | biotite.structure.AtomArrayStack:
    """Convert PoseStack back to Biotite structure.

    Args:
        pose_stack: Pose stack to convert.
        co: Canonical ordering used for conversion. Provide the ordering that
            was used when ligands or custom residue types are present.

    Returns:
        Biotite AtomArray for single-pose or AtomArrayStack for multi-pose.
    """
    if co is None:
        co = canonical_ordering_for_biotite()
    cf = canonical_form_from_pose_stack(co, pose_stack)
    return biotite_from_canonical_form(cf, co=co)


def _map_atoms_to_canonical(co, connect, atom_res_inds, res_names, atom_names):
    """Map Biotite atom names to canonical ordering indices.

    Suppresses atoms that conflict with block type resolution:
    - "H" on N-terminal residues (CIF amide H vs tmol's H1/H2/H3)
    - "OXT" on non-C-terminal residues (CIF chain-break OXT)

    The ``connect`` array must already incorporate chain boundaries
    (see ``canonical_form_from_biotite``).

    Returns (valid_atom_mask, valid_atom_inds, valid_res_inds).
    """
    is_nterm_atom = ~connect[atom_res_inds, 0]
    is_cterm_atom = ~connect[atom_res_inds, 1]

    atom_inds = []
    valid = []
    for i, (resname, atname) in enumerate(zip(res_names, atom_names)):
        mapping = co.restypes_atom_index_mapping.get(resname, {})
        idx = mapping.get(atname, -1)
        if idx >= 0:
            if atname == "H" and is_nterm_atom[i]:
                idx = -1
            elif atname == "OXT" and not is_cterm_atom[i]:
                idx = -1
        atom_inds.append(idx)
        valid.append(idx >= 0)

    valid_atom_mask = numpy.array(valid)
    atom_inds_arr = numpy.array(atom_inds)
    return (
        valid_atom_mask,
        atom_inds_arr[valid_atom_mask],
        atom_res_inds[valid_atom_mask],
    )


def _res_names_for_structure(
    biotite_structure: biotite.structure.AtomArray | biotite.structure.AtomArrayStack,
):
    if isinstance(biotite_structure, biotite.structure.AtomArrayStack):
        return biotite_structure[0].res_name
    return biotite_structure.res_name


def _filter_supported_atoms_and_connectivity(
    biotite_structure: biotite.structure.AtomArray | biotite.structure.AtomArrayStack,
    co: CanonicalOrdering,
):
    biotite_residues = biotite.structure.get_residues(biotite_structure)[1]
    to_remove = {"HOH"}
    known_residue_names = set(co.restype_io_equiv_classes)
    for i_3lc in biotite_residues:
        if i_3lc in to_remove:
            continue
        if i_3lc not in known_residue_names:
            logger.warning("Unrecognized 3lc %s", i_3lc)
            to_remove.add(i_3lc)

    res_names = _res_names_for_structure(biotite_structure)
    valid_atoms = numpy.array([name not in to_remove for name in res_names])
    biotite_residue_starts = biotite.structure.get_residue_starts(biotite_structure)
    valid_res = valid_atoms[biotite_residue_starts]

    lower = numpy.roll(valid_res, 1)
    lower[0] = True
    lower = lower[valid_res]
    upper = numpy.roll(valid_res, -1)
    upper[-1] = True
    upper = upper[valid_res]
    connect = numpy.invert(numpy.column_stack((lower, upper)))

    if isinstance(biotite_structure, biotite.structure.AtomArrayStack):
        biotite_structure = biotite_structure[:, valid_atoms]
    else:
        biotite_structure = biotite_structure[valid_atoms]

    return biotite_structure, connect


def _extract_residue_metadata(
    biotite_structure: biotite.structure.AtomArray | biotite.structure.AtomArrayStack,
    connect,
    torch_device: torch.device,
):
    biotite_residue_starts = biotite.structure.get_residue_starts(biotite_structure)
    biotite_chain_id_for_res = biotite.structure.chains.get_all_chain_positions(
        biotite_structure
    )[biotite_residue_starts]

    if len(biotite_chain_id_for_res) > 1:
        chain_breaks = biotite_chain_id_for_res[1:] != biotite_chain_id_for_res[:-1]
        connect[1:, 0] &= ~chain_breaks
        connect[:-1, 1] &= ~chain_breaks

    res_not_connected_1 = torch.tensor(
        connect, dtype=torch.bool, device=torch_device
    ).unsqueeze(0)
    biotite_chain_labels = biotite_structure.chain_id[biotite_residue_starts]
    biotite_insertion_codes = biotite_structure.ins_code[biotite_residue_starts]
    biotite_residue_labels, biotite_residues = biotite.structure.get_residues(
        biotite_structure
    )
    return (
        biotite_chain_id_for_res,
        biotite_chain_labels,
        biotite_insertion_codes,
        biotite_residue_labels,
        biotite_residues,
        res_not_connected_1,
        connect,
    )


def _populate_canonical_coords(
    biotite_structure: biotite.structure.AtomArray | biotite.structure.AtomArrayStack,
    torch_device: torch.device,
    co: CanonicalOrdering,
    biotite_residues,
    valid_atom_mask,
    valid_res_inds,
    valid_atom_inds,
):
    n_poses = 1
    if isinstance(biotite_structure, biotite.structure.AtomArrayStack):
        n_poses = biotite_structure.coord.shape[0]

    tmol_coords = torch.full(
        (n_poses, len(biotite_residues), co.max_n_canonical_atoms, 3),
        numpy.nan,
        dtype=torch.float32,
        device=torch_device,
    )
    biotite_coords = torch.tensor(biotite_structure.coord, device=torch_device)

    if n_poses == 1:
        tmol_coords[0, valid_res_inds, valid_atom_inds] = biotite_coords[
            valid_atom_mask
        ]
    else:
        for pose_ind in range(n_poses):
            tmol_coords[pose_ind, valid_res_inds, valid_atom_inds] = biotite_coords[
                pose_ind
            ][valid_atom_mask]
    return tmol_coords, n_poses


def _populate_optional_atom_metadata(
    biotite_structure: biotite.structure.AtomArray | biotite.structure.AtomArrayStack,
    n_poses: int,
    n_residues: int,
    max_n_canonical_atoms: int,
    valid_res_inds,
    valid_atom_inds,
    valid_atom_mask,
):
    biotite_b_factors = None
    biotite_occupancy = None

    if hasattr(biotite_structure, "b_factor"):
        b_factor = numpy.asarray(biotite_structure.b_factor)
        biotite_b_factors = numpy.full(
            (n_poses, n_residues, max_n_canonical_atoms),
            0,
            dtype=numpy.float32,
        )
        if n_poses == 1 or b_factor.ndim == 1:
            biotite_b_factors[:, valid_res_inds, valid_atom_inds] = b_factor[
                valid_atom_mask
            ]
        else:
            for pose_ind in range(n_poses):
                biotite_b_factors[pose_ind, valid_res_inds, valid_atom_inds] = b_factor[
                    pose_ind
                ][valid_atom_mask]

    if hasattr(biotite_structure, "occupancy"):
        occupancy = numpy.asarray(biotite_structure.occupancy)
        biotite_occupancy = numpy.full(
            (n_poses, n_residues, max_n_canonical_atoms),
            0,
            dtype=numpy.float32,
        )
        if n_poses == 1 or occupancy.ndim == 1:
            biotite_occupancy[:, valid_res_inds, valid_atom_inds] = occupancy[
                valid_atom_mask
            ]
        else:
            for pose_ind in range(n_poses):
                biotite_occupancy[pose_ind, valid_res_inds, valid_atom_inds] = (
                    occupancy[pose_ind][valid_atom_mask]
                )
    return biotite_b_factors, biotite_occupancy


@validate_args
def canonical_form_from_biotite(
    biotite_structure: biotite.structure.AtomArray | biotite.structure.AtomArrayStack,
    torch_device: torch.device,
    co: CanonicalOrdering | None = None,
) -> CanonicalForm:
    """Convert a Biotite AtomArray or AtomArrayStack to a CanonicalForm.

    This function bridges between Biotite's data structures and tmol's internal
    representation by converting atom and residue information from string-based
    identifiers to tmol's canonical integer-based indexing system.

    The conversion process involves:
    1. Extracting residue and atom information from the Biotite structure
    2. Mapping Biotite residue names to tmol's canonical residue type indices
    3. Mapping atom names to canonical atom indices for each residue type
    4. Constructing coordinate tensors with proper NaN handling for missing atoms
    5. Preserving optional metadata (B-factors, occupancy, chain labels, etc.)

    Args:
        biotite_structure: A Biotite AtomArray (single structure) or
            AtomArrayStack (multiple structures) containing the molecular data.
            Must contain atom coordinates, residue names, atom names, chain IDs,
            and optionally B-factors and occupancy values.
        torch_device: PyTorch device (e.g., torch.device('cuda') or torch.device('cpu'))
            where the resulting tensors should be allocated.

    Returns:
        CanonicalForm: A data structure containing:
            - chain_id: Tensor mapping residues to chain indices
            - res_types: Tensor mapping residues to tmol residue type indices
            - coords: 4D tensor of atomic coordinates (poses x residues x atoms x 3)
            - res_labels: Original residue sequence numbers from the structure
            - residue_insertion_codes: PDB insertion codes for residues
            - chain_labels: Original chain identifiers from the structure
            - atom_occupancy: Optional tensor of atom occupancy values
            - atom_b_factor: Optional tensor of atom B-factor values
            - disulfides: None (not handled in this conversion)
            - res_not_connected: None (not handled in this conversion)

    Notes:
        - Missing atoms are represented as NaN coordinates in the output tensor
        - For AtomArrayStack inputs, metadata is replicated across all poses
        - The function handles both standard amino acids and special variants like HIS_D
        - B-factor and occupancy data are preserved if present in the input structure
        - Chain labels are limited to single characters as per Biotite's AtomArray design
    """
    if co is None:
        co = canonical_ordering_for_biotite()

    biotite_structure, connect = _filter_supported_atoms_and_connectivity(
        biotite_structure, co
    )
    (
        biotite_chain_id_for_res,
        biotite_chain_labels,
        biotite_insertion_codes,
        biotite_residue_labels,
        biotite_residues,
        res_not_connected_1,
        connect,
    ) = _extract_residue_metadata(biotite_structure, connect, torch_device)

    atom_res_inds = biotite.structure.get_all_residue_positions(biotite_structure)
    biotite_name_for_atom = biotite_structure.atom_name
    biotite_res_name_for_atom = biotite_structure.res_name

    restype_to_index = {name: i for i, name in enumerate(co.restype_io_equiv_classes)}
    tmol_restypes = [restype_to_index[i_3lc] for i_3lc in biotite_residues]

    valid_atom_mask, valid_atom_inds, valid_res_inds = _map_atoms_to_canonical(
        co, connect, atom_res_inds, biotite_res_name_for_atom, biotite_name_for_atom
    )
    tmol_coords, n_poses = _populate_canonical_coords(
        biotite_structure,
        torch_device,
        co,
        biotite_residues,
        valid_atom_mask,
        valid_res_inds,
        valid_atom_inds,
    )
    biotite_b_factors, biotite_occupancy = _populate_optional_atom_metadata(
        biotite_structure,
        n_poses,
        len(biotite_residues),
        co.max_n_canonical_atoms,
        valid_res_inds,
        valid_atom_inds,
        valid_atom_mask,
    )

    # ========================================
    # 7. Prepare metadata for output
    # ========================================

    def copy_for_all_poses(dat):
        return numpy.repeat(dat[numpy.newaxis, ...], n_poses, axis=0)

    biotite_residue_labels = copy_for_all_poses(biotite_residue_labels)
    biotite_chain_labels = copy_for_all_poses(biotite_chain_labels)
    biotite_insertion_codes = copy_for_all_poses(biotite_insertion_codes)

    chain_id = (
        torch.tensor(biotite_chain_id_for_res, dtype=torch.int32, device=torch_device)
        .unsqueeze(0)
        .repeat(n_poses, 1)
    )
    res_types = (
        torch.tensor(tmol_restypes, dtype=torch.int32, device=torch_device)
        .unsqueeze(0)
        .repeat(n_poses, 1)
    )
    res_not_connected = res_not_connected_1.repeat(n_poses, 1, 1)

    # ========================================
    # 8. Return CanonicalForm with all converted data
    # ========================================
    return CanonicalForm(
        chain_id=chain_id,
        res_types=res_types,
        coords=tmol_coords,
        chain_labels=biotite_chain_labels.astype(object),
        res_labels=biotite_residue_labels,
        residue_insertion_codes=biotite_insertion_codes.astype(object),
        atom_occupancy=biotite_occupancy,
        atom_b_factor=biotite_b_factors,
        disulfides=None,
        res_not_connected=res_not_connected,
    )


@toolz.functoolz.memoize
def _paramdb_for_biotite() -> ParameterDatabase:
    """For Biotite, let's just get the default param DB.
    We shouldn't need a subset since we're mapping from strings(?)"""

    # from tmol.extern.rosettafold2.chemical import num2aa

    # desired_rt_names = sorted(num2aa[:20] + ["HIS_D", "CYD"])
    # desired_rt_names = sorted(resnames.tolist() + ["HIS_D", "CYD"])
    # hard coding
    # desired_variants_display_names = ["nterm", "cterm"]

    return ParameterDatabase.get_default()


@toolz.functoolz.memoize
def _restype_set_for_biotite() -> ResidueTypeSet:
    paramdb = _paramdb_for_biotite()
    return ResidueTypeSet.from_database(paramdb.chemical)


@validate_args
@toolz.functoolz.memoize
def canonical_ordering_for_biotite() -> CanonicalOrdering:
    """Construct the CanonicalOrdering object to use for Biotite.
    This wont be used as a typical CanonicalOrdering object, since
    we aren't mapping from int-to-int, and instead are going from
    string-to-int.
    """

    paramdb = _paramdb_for_biotite()
    return CanonicalOrdering.from_chemdb(paramdb.chemical)


@validate_args
@toolz.functoolz.memoize
def packed_block_types_for_biotite(device: torch.device) -> PackedBlockTypes:
    """Construct the PackedBlockTypes (PBT) object that will used for Biotite.
    We'll use the defaults since anything might show up in a Biotite AtomArray.
    Some things may show up in the AtomArrays that are not handled by this
    PBT, but that is work for the future.
    """

    restype_set = _restype_set_for_biotite()

    return PackedBlockTypes.from_restype_list(
        restype_set.chem_db, restype_set, restype_set.residue_types, device
    )


def _derived_types_for_param_db(
    param_db: ParameterDatabase, device: torch.device
) -> tuple[CanonicalOrdering, ResidueTypeSet, PackedBlockTypes]:
    """Build canonical ordering and packed block types from a DB."""
    co = CanonicalOrdering.from_chemdb(param_db.chemical)
    rts = ResidueTypeSet.from_database(param_db.chemical)
    pbt = PackedBlockTypes.from_restype_list(
        rts.chem_db, rts, rts.residue_types, device
    )
    return co, rts, pbt


def get_element_from_atom_name(atom_name: str) -> str:
    """
    Parses a 4-character PDB atom name to return the element symbol.
    PDB columns 13-16:
    - Elements with 2 letters start at col 13.
    - Elements with 1 letter start at col 14.
    """
    # Remove whitespace
    stripped = atom_name.strip()

    # If the first character is a digit (e.g., '1HE2'), it's a Hydrogen
    if stripped[0].isdigit():
        return "H"

    # According to PDB specs, if the atom name is 4 chars long and
    # starts with H, it is Hydrogen.
    if len(atom_name) == 4 and atom_name[0] == "H":
        return "H"

    # Otherwise, the first 1 or 2 non-digit characters are the element
    # This regex-free approach works for 99% of PDB files
    element = ""
    for char in stripped:
        if char.isalpha():
            element += char
            # Most elements are 1 or 2 letters;
            # amino acid side chains use the first letter as the element.
            if len(element) == 2:
                # Common 2-letter ions/elements
                if element.upper() in ["FE", "MG", "CL", "ZN", "NA", "CU"]:
                    return element.capitalize()
                else:
                    # It's likely a 1-letter element with a branch ID (e.g., 'CA')
                    return element[0].upper()
        else:
            break

    return element.upper()


@validate_args
def biotite_from_canonical_form(
    cf: CanonicalForm,
    co: CanonicalOrdering | None = None,
) -> biotite.structure.AtomArray | biotite.structure.AtomArrayStack:
    import biotite.structure as struc

    if co is None:
        co = canonical_ordering_for_biotite()
    # rts = _restype_set_for_biotite()

    n_poses = cf.coords.size(0)
    n_residues = cf.coords.size(1)
    max_atoms = cf.coords.size(2)

    if n_poses > 1 and not _poses_have_identical_metadata(cf):
        raise ValueError(
            "Cannot convert CanonicalForm with multiple poses to biotite structure: "
            "poses have different metadata (chain_id, res_types, res_labels, "
            "residue_insertion_codes, or chain_labels). "
            "Only coordinate differences are allowed for multi-pose conversion."
        )

    # For multi-pose (NMR) structures, all poses must have the same atom
    # annotations. Use the union of non-NaN atoms across all poses to build
    # a consistent atom list; missing atoms in individual poses get NaN coords.
    atom_mask = torch.any(~torch.isnan(cf.coords[:, :, :, 0]), dim=0)

    template_atoms = []
    atom_indices = []
    for res_id in range(n_residues):
        chain_label = cf.chain_labels[0, res_id]
        res_label = cf.res_labels[0, res_id]
        res_type_id = cf.res_types[0, res_id].cpu()

        res_name = co.restype_io_equiv_classes[res_type_id]
        atom_name_list = co.restypes_ordered_atom_names[res_name]

        for atom_id in range(min(max_atoms, len(atom_name_list))):
            if not atom_mask[res_id, atom_id]:
                continue

            atom_name = atom_name_list[atom_id]
            template_atoms.append(
                struc.Atom(
                    [0.0, 0.0, 0.0],
                    chain_id=chain_label,
                    res_id=res_label,
                    res_name=res_name,
                    atom_name=atom_name,
                    element=get_element_from_atom_name(atom_name),
                    b_factor=(
                        cf.atom_b_factor[0, res_id, atom_id]
                        if cf.atom_b_factor is not None
                        else None
                    ),
                    occupancy=(
                        cf.atom_occupancy[0, res_id, atom_id]
                        if cf.atom_occupancy is not None
                        else None
                    ),
                )
            )
            atom_indices.append((res_id, atom_id))

    template = struc.array(template_atoms)

    if n_poses == 1:
        for i, (res_id, atom_id) in enumerate(atom_indices):
            template.coord[i] = cf.coords[0, res_id, atom_id].cpu().numpy()
        return template

    poses = []
    for pose_id in range(n_poses):
        arr = template.copy()
        for i, (res_id, atom_id) in enumerate(atom_indices):
            c = cf.coords[pose_id, res_id, atom_id].cpu()
            if torch.isnan(c).any():
                arr.coord[i] = [float("nan")] * 3
            else:
                arr.coord[i] = c.numpy()
        poses.append(arr)
    return struc.stack(poses)


@validate_args
def _poses_have_identical_metadata(cf: CanonicalForm) -> bool:
    """Check if all poses in the CanonicalForm have identical metadata.

    Returns True if all poses have the same:
    - chain_id
    - res_types
    - res_labels
    - residue_insertion_codes
    - chain_labels

    Only coordinates are allowed to differ between poses.
    """
    n_poses = cf.coords.size(0)

    if n_poses <= 1:
        return True

    # Check chain_id
    if not torch.all(cf.chain_id[0] == cf.chain_id[1:]).item():
        return False

    # Check res_types
    if not torch.all(cf.res_types[0] == cf.res_types[1:]).item():
        return False

    # Check res_labels (numpy array comparison)
    for pose_id in range(1, n_poses):
        if not numpy.array_equal(cf.res_labels[0], cf.res_labels[pose_id]):
            return False

    # Check residue_insertion_codes (numpy object array comparison)
    for pose_id in range(1, n_poses):
        if not numpy.array_equal(
            cf.residue_insertion_codes[0], cf.residue_insertion_codes[pose_id]
        ):
            return False

    # Check chain_labels (numpy object array comparison)
    for pose_id in range(1, n_poses):
        if not numpy.array_equal(cf.chain_labels[0], cf.chain_labels[pose_id]):
            return False

    return True
