import torch
import numpy
import toolz
import biotite

from typing import List, Mapping
from tmol.types.functional import validate_args
from tmol.types.torch import Tensor
from tmol.chemical.restypes import ResidueTypeSet
from tmol.database import ParameterDatabase
from tmol.io.canonical_form import CanonicalForm
from tmol.io.canonical_ordering import CanonicalOrdering
from tmol.pose.packed_block_types import PackedBlockTypes
from tmol.pose.pose_stack import PoseStack


def load_ubq(pdb="1ubq.pdb"):
    import biotite.structure.io

    device = torch.device("cuda", torch.cuda.current_device())
    ubq = biotite.structure.io.load_structure(pdb)
    return pose_stack_from_biotite(ubq, device)
    # ubq_cf,names = canonical_form_from_biotite(ubq, device)
    # biotite_from_canonical_form(ubq_cf)


@validate_args
def pose_stack_from_biotite(
    biotite_structure,
    torch_device,
    **kwargs,
) -> PoseStack:
    """Build a PoseStack from the output generated by Biotite"""
    from tmol.io.pose_stack_construction import pose_stack_from_canonical_form

    cf, resnames = canonical_form_from_biotite(biotite_structure, torch_device)

    co = canonical_ordering_for_biotite(resnames)
    pbt = packed_block_types_for_biotite(resnames, cf.coords.device)

    return pose_stack_from_canonical_form(co, pbt, *cf, **kwargs)


# @validate_args # TODO
def canonical_form_from_biotite(biotite_structure, torch_device) -> CanonicalForm:
    """The canonical form is intended to represent a stable, serializable intermediate format
    for a structure so that it can be created today and then be read in years from now
    and be used to construct a PoseStack in tmol. As residue types are integers,
    this means that we must guarantee stability of these integer representations, but it also
    means that you the user must build a PoseStack using the carefully constructed objects
    returned by the canonical_ordering_for_rosettafold2 and packed_block_types_for_rosettafold2
    functions.
    """

    device = torch_device
    n_poses = 1
    if biotite_structure is biotite.structure.AtomArrayStack:
        n_poses = biotite_structure.coord.shape[0]

    biotite_residue_starts = biotite.structure.get_residue_starts(biotite_structure)
    biotite_chain_id_for_res = biotite.structure.chains.get_all_chain_positions(
        biotite_structure
    )[biotite_residue_starts]
    biotite_res_ind_for_atom = biotite.structure.get_all_residue_positions(
        biotite_structure
    )  # res_id
    biotite_name_for_atom = biotite_structure.atom_name
    biotite_res_name_for_atom = biotite_structure.res_name

    # get the tmol residue indices
    biotite_residues = biotite.structure.get_residues(biotite_structure)[1]
    biotite_residue_names = numpy.unique(biotite_residues)

    co = canonical_ordering_for_biotite(biotite_residue_names)

    tmol_restypes = [
        co.restype_io_equiv_classes.index(i_3lc) for i_3lc in biotite_residues
    ]
    atom_mapping = [
        co.restypes_atom_index_mapping[resname][atname]
        for resname, atname in zip(biotite_res_name_for_atom, biotite_name_for_atom)
    ]

    tmol_coords = torch.full(
        (n_poses, len(biotite_residues), co.max_n_canonical_atoms, 3),
        numpy.nan,
        dtype=torch.float32,
        device=device,
    )
    pose_inds = torch.zeros(
        (len(biotite_structure.res_id),), dtype=torch.int32, device=torch_device
    )
    res_inds = torch.tensor(biotite_res_ind_for_atom, device=torch_device)
    atom_inds = torch.tensor(atom_mapping, device=torch_device)
    biotite_coords = torch.tensor(biotite_structure.coord, device=torch_device)

    print(pose_inds.shape)
    print(res_inds.shape)
    print(atom_inds.shape)
    print(biotite_coords.shape)

    print(pose_inds.max())
    print(res_inds.max())
    print(atom_inds.max())

    for pose_ind in range(n_poses):
        tmol_coords[pose_ind, res_inds, atom_inds] = biotite_coords[pose_ind]

    # res_chain_id = torch.zeros((1, len(tmol_restypes)), dtype=torch.int32, device=torch_device)
    chain_id = (
        torch.tensor(biotite_chain_id_for_res, dtype=torch.int32, device=torch_device)
        .unsqueeze(0)
        .repeat(n_poses, 1)
    )  # TODO
    res_types = (
        torch.tensor(tmol_restypes, dtype=torch.int32, device=torch_device)
        .unsqueeze(0)
        .repeat(n_poses, 1)
    )
    print("RESTYPE SHAPE", res_types.shape)
    # torch.set_printoptions(threshold=10_000)
    # print(chain_id)
    # print(res_types)
    return (
        CanonicalForm(
            chain_id=chain_id,  # TODO
            res_types=res_types,
            coords=tmol_coords,
            chain_labels=None,
            res_labels=None,
            residue_insertion_codes=None,
            atom_occupancy=None,
            atom_b_factor=None,
            disulfides=None,
            res_not_connected=None,
        ),
        biotite_residue_names,
    )


def biotite_from_canonical_form(cf):
    print(cf.res_types.unique())
    rts = _restype_set_for_biotite(cf.res_types.unique())

    for pose_ind in range(cf.coords.shape[0]):
        for residue_ind in range(cf.coords.shape[1]):
            for atom_ind in range(cf.coords.shape[2]):
                coords = cf.coords[pose_ind, residue_ind, atom_ind]
                chain_id = cf.chain_id[pose_ind, residue_ind]
                res_type = cf.res_types[pose_ind, residue_ind]
                res_name = res_type


# @toolz.functoolz.memoize
def _paramdb_for_biotite(resnames) -> ParameterDatabase:
    """Construct the paramdb representing the subset of residues that
    are "used" in Rosettafold2: the canonical amino acids (including the
    two histidine tautomers and the disulfid-bonded cysteine) and
    the canonical n- and c-termini patches.
    """

    # from tmol.extern.rosettafold2.chemical import num2aa

    # desired_rt_names = sorted(num2aa[:20] + ["HIS_D", "CYD"])
    desired_rt_names = sorted(resnames.tolist() + ["HIS_D", "CYD"])
    # hard coding
    desired_variants_display_names = ["nterm", "cterm"]

    return ParameterDatabase.get_default().create_stable_subset(
        desired_rt_names, desired_variants_display_names
    )


# @toolz.functoolz.memoize
def _restype_set_for_biotite(resnames) -> ResidueTypeSet:
    paramdb = _paramdb_for_biotite(resnames)
    return ResidueTypeSet.from_database(paramdb.chemical)


@validate_args
# @toolz.functoolz.memoize
def canonical_ordering_for_biotite(resnames) -> CanonicalOrdering:
    """Construct the CanonicalOrdering object that will be used for the
    subset of residue types that are used by RoseTTAFold2; this will be
    stable so that the entries in "coords" tensor member of the canonical
    form dictionary will be interpretable indefinitely and thus a
    canonical form dictionary can be serialized to disk and read again
    after an arbitrary amount of time
    """

    paramdb = _paramdb_for_biotite(resnames)
    return CanonicalOrdering.from_chemdb(paramdb.chemical)


@validate_args
# @toolz.functoolz.memoize
def packed_block_types_for_biotite(resnames, device: torch.device) -> PackedBlockTypes:
    """Construct the PackedBlockTypes (PBT) object that will be used for
    the subset of residue types that are used by RoseTTAFold2. For efficiency
    we use the same PBT in the creation of multiple PoseStacks. Thus
    we memoize this function. The user will only interact with this
    function if they are constructing PoseStacks from deserialized
    canonical form objects. See canonical_form_from_rosettafold2 for details.
    """

    restype_set = _restype_set_for_biotite(resnames)

    return PackedBlockTypes.from_restype_list(
        restype_set.chem_db, restype_set, restype_set.residue_types, device
    )


@toolz.functoolz.memoize
def _get_rf2_2_tmol_mappings(device: torch.device):
    # TO DO: How should we handle the "UNK" and "MAS" RTs?
    # They list ALA atoms; we could reasonably treat them as ALA
    # but that does not seem the point of having these residues.

    co = canonical_ordering_for_rosettafold2()
    from tmol.extern.rosettafold2.chemical import (
        num2aa,
        aa2long,
    )

    rf2_atom_names_for_name3s = {
        x: [at.strip() if at is not None else "" for at in y]
        for x, y in zip(num2aa, aa2long)
    }

    (rt_map, atname_map, at_is_real) = co.create_src_2_tmol_mappings(
        num2aa, rf2_atom_names_for_name3s, device
    )

    # also want to turn off n-term "H" atoms
    supress_atom_at_nterm = torch.zeros(
        (
            len(num2aa),
            co.max_n_canonical_atoms,
        ),
        dtype=torch.bool,
        device=device,
    )
    for i, i_3lc in enumerate(num2aa):
        if i_3lc not in co.restype_io_equiv_classes:
            continue
        for atname in rf2_atom_names_for_name3s[i_3lc]:
            if atname.strip() == "H":
                tmol_ind = co.restypes_atom_index_mapping[i_3lc][atname.strip()]
                supress_atom_at_nterm[i, tmol_ind] = True
    return rt_map, atname_map, at_is_real, supress_atom_at_nterm
