"""Molecular charge computation for ligands.

MMFF94 partial charges are the only automatic charge method used in the
pipeline. If MMFF94 cannot parameterize a molecule, preparation fails with
an actionable error instead of silently switching charge models.
"""

from typing import Mapping, Optional

from rdkit import Chem
from rdkit.Chem import AllChem

from tmol.ligand.atom_typing import AtomTypeAssignment


def _name_sort_key(name: str) -> tuple[str, int]:
    """Create a natural sort key for atom names with numeric suffixes.

    Args:
        name: Atom name such as ``C12``.

    Returns:
        Tuple of alphabetic prefix and numeric suffix for stable sorting.
    """
    i = len(name)
    while i > 0 and name[i - 1].isdigit():
        i -= 1
    prefix = name[:i]
    suffix = name[i:]
    return (prefix, int(suffix) if suffix else -1)


def _mmff_diagnostics(mol: Chem.Mol) -> str:
    """Return a compact diagnostic string for MMFF parameterization failures."""
    has_all = False
    try:
        has_all = bool(AllChem.MMFFHasAllMoleculeParams(mol))
    except Exception:
        has_all = False
    try:
        smiles = Chem.MolToSmiles(Chem.RemoveHs(Chem.Mol(mol)), isomericSmiles=True)
    except Exception:
        smiles = "<smiles-unavailable>"

    atom_summaries = []
    for atom in mol.GetAtoms():
        atom_summaries.append(
            (
                f"{atom.GetIdx()}:{atom.GetSymbol()}(q={atom.GetFormalCharge()},"
                f"deg={atom.GetDegree()},aro={int(atom.GetIsAromatic())},"
                f"ring={int(atom.IsInRing())})"
            )
        )

    return (
        f"MMFFHasAllMoleculeParams={has_all}; "
        f"num_atoms={mol.GetNumAtoms()}; "
        f"smiles={smiles}; "
        f"atoms=[{', '.join(atom_summaries)}]"
    )


def compute_mmff94_charges(mol: Chem.Mol) -> dict[int, float]:
    """Compute MMFF94 partial charges via RDKit.

    Raises:
        RuntimeError: If RDKit cannot parameterize MMFF94 charges for ``mol``.
    """
    try:
        props = AllChem.MMFFGetMoleculeProperties(mol, mmffVariant="MMFF94")
    except Exception as exc:
        raise RuntimeError(
            "MMFF94 parameterization threw an exception. " f"{_mmff_diagnostics(mol)}"
        ) from exc
    if props is None:
        raise RuntimeError(
            "MMFF94 parameterization returned no properties. "
            f"{_mmff_diagnostics(mol)}"
        )
    return {i: props.GetMMFFPartialCharge(i) for i in range(mol.GetNumAtoms())}


def build_partial_charges(
    mol: Chem.Mol,
    atom_types: list[AtomTypeAssignment],
    input_charges: Optional[Mapping[str, float]] = None,
    ligand_name: Optional[str] = None,
    charge_mode: str = "auto",
) -> dict[str, float]:
    """Return ``{atom_name: partial_charge}`` for every atom in ``atom_types``.

    Authoritative caller-supplied charges (e.g. AM1-BCC from mol2/CIF) win
    when present in ``charge_mode="auto"``. Remaining atoms fall back to MMFF94,
    and failures are surfaced to the caller.
    """
    mode = charge_mode.lower().strip()
    if mode not in {"auto", "input", "mmff94"}:
        raise ValueError(
            f"Unsupported charge_mode={charge_mode!r}. "
            "Expected one of: 'auto', 'input', 'mmff94'."
        )

    by_name = {} if mode == "mmff94" else dict(input_charges or {})
    if by_name:
        missing_from_input = [at for at in atom_types if at.atom_name not in by_name]
        if missing_from_input:
            # When hydrogens are regenerated by RDKit, names can differ
            # (e.g. source H1/H2 vs generated HC1/HC2). Bridge those
            # deterministically so authoritative source charges still apply.
            missing_non_h = [at for at in missing_from_input if at.element != "H"]
            if not missing_non_h:
                atom_names = {at.atom_name for at in atom_types}
                source_h = [
                    name
                    for name in by_name
                    if name not in atom_names and name.startswith("H")
                ]
                if len(source_h) >= len(missing_from_input):
                    source_h_sorted = sorted(source_h, key=_name_sort_key)
                    missing_h_sorted = sorted(
                        missing_from_input, key=lambda at: at.index
                    )
                    for at, src_name in zip(missing_h_sorted, source_h_sorted):
                        by_name[at.atom_name] = by_name[src_name]
                    missing_from_input = [
                        at for at in atom_types if at.atom_name not in by_name
                    ]
        if not missing_from_input:
            return {at.atom_name: by_name[at.atom_name] for at in atom_types}
    else:
        missing_from_input = list(atom_types)

    if mode == "input":
        prefix = f"{ligand_name}: " if ligand_name else ""
        missing_names = ", ".join(at.atom_name for at in missing_from_input)
        raise RuntimeError(
            f"{prefix}authoritative input charges are required (charge_mode='input') "
            f"but missing for atoms: [{missing_names}]"
        )
    try:
        by_index = compute_mmff94_charges(mol)
    except RuntimeError as exc:
        prefix = f"{ligand_name}: " if ligand_name else ""
        missing_names = ", ".join(at.atom_name for at in missing_from_input)
        raise RuntimeError(
            f"{prefix}partial-charge generation failed. "
            "No Gasteiger fallback is used; provide authoritative input "
            "charges or fix MMFF94 parameterization. "
            "For CIF inputs, load with biotite using include_bonds=True and "
            "include per-atom partial charges when available "
            "(e.g. extra_fields=['partial_charge']). "
            "Alternatively, provide pre-parameterized ligand_params_files. "
            f"Atoms requiring MMFF charges: [{missing_names}]. "
            f"Details: {exc}"
        ) from exc
    charges: dict[str, float] = {}
    for at in atom_types:
        if at.atom_name in by_name:
            charges[at.atom_name] = by_name[at.atom_name]
        elif at.index in by_index:
            charges[at.atom_name] = by_index[at.index]
    return charges
