"""Molecular charge computation for ligands.

MMFF94 partial charges are the only charge method in the pipeline. They are
computed via OpenBabel: RDKit's MMFF requires a strictly sanitizable graph and
rejects valid-but-awkward states (protonated amines, hypervalent sulfur,
fused-aromatic systems that don't kekulize cleanly), whereas OpenBabel
re-perceives valence/aromaticity and parameterizes MMFF94 directly -- so no
formal-charge or kekulization repair of the RDKit mol is needed.
"""

from typing import Mapping, Optional

from openbabel import openbabel, pybel
from rdkit import Chem

from tmol.ligand.atom_typing import AtomTypeAssignment

# OpenBabel's Mol-block reader logs benign kekulization/valence warnings (it
# re-perceives chemistry itself); silence them so they don't flood test output.
try:
    openbabel.obErrorLog.SetOutputLevel(openbabel.obError)
except Exception:  # pragma: no cover - guard against OB API drift
    pass


def _name_sort_key(name: str) -> tuple[str, int]:
    """Create a natural sort key for atom names with numeric suffixes.

    Args:
        name: Atom name such as ``C12``.

    Returns:
        Tuple of alphabetic prefix and numeric suffix for stable sorting.
    """
    i = len(name)
    while i > 0 and name[i - 1].isdigit():
        i -= 1
    prefix = name[:i]
    suffix = name[i:]
    return (prefix, int(suffix) if suffix else -1)


def compute_mmff94_charges(mol: Chem.Mol) -> dict[int, float]:
    """Compute MMFF94 partial charges via OpenBabel.

    The molecule is handed to OpenBabel as a Mol block (``kekulize=False`` so
    RDKit's kekulization gate -- which rejects the protonated / hypervalent /
    fused systems we need -- is never hit). OpenBabel re-perceives chemistry and
    assigns MMFF94 charges directly, with no formal-charge repair required.
    Mol-block atom order is preserved, so the returned charges are keyed by the
    input atom index.

    Raises:
        RuntimeError: if OpenBabel cannot assign MMFF94 charges. No Gasteiger
            fallback is used -- the caller must supply authoritative charges.
    """
    mol_block = Chem.MolToMolBlock(mol, kekulize=False)
    obmol = pybel.readstring("mol", mol_block)
    charge_model = openbabel.OBChargeModel.FindType("mmff94")
    if charge_model is None or not charge_model.ComputeCharges(obmol.OBMol):
        raise RuntimeError("OpenBabel MMFF94 parameterization failed")
    return {
        atom.GetIndex(): float(atom.GetPartialCharge())
        for atom in openbabel.OBMolAtomIter(obmol.OBMol)
    }


def build_partial_charges(
    mol: Chem.Mol,
    atom_types: list[AtomTypeAssignment],
    input_charges: Optional[Mapping[str, float]] = None,
    ligand_name: Optional[str] = None,
    charge_mode: str = "auto",
) -> dict[str, float]:
    """Return ``{atom_name: partial_charge}`` for every atom in ``atom_types``.

    Authoritative caller-supplied charges (e.g. AM1-BCC from mol2/CIF) win
    when present in ``charge_mode="auto"``. Remaining atoms fall back to MMFF94,
    and failures are surfaced to the caller.
    """
    mode = charge_mode.lower().strip()
    if mode not in {"auto", "input", "mmff94"}:
        raise ValueError(
            f"Unsupported charge_mode={charge_mode!r}. "
            "Expected one of: 'auto', 'input', 'mmff94'."
        )

    by_name = {} if mode == "mmff94" else dict(input_charges or {})
    if by_name:
        missing_from_input = [at for at in atom_types if at.atom_name not in by_name]
        if missing_from_input:
            # When hydrogens are regenerated by RDKit, names can differ
            # (e.g. source H1/H2 vs generated HC1/HC2). Bridge those
            # deterministically so authoritative source charges still apply.
            missing_non_h = [at for at in missing_from_input if at.element != "H"]
            if not missing_non_h:
                atom_names = {at.atom_name for at in atom_types}
                source_h = [
                    name
                    for name in by_name
                    if name not in atom_names and name.startswith("H")
                ]
                if len(source_h) >= len(missing_from_input):
                    source_h_sorted = sorted(source_h, key=_name_sort_key)
                    missing_h_sorted = sorted(
                        missing_from_input, key=lambda at: at.index
                    )
                    for at, src_name in zip(missing_h_sorted, source_h_sorted):
                        by_name[at.atom_name] = by_name[src_name]
                    missing_from_input = [
                        at for at in atom_types if at.atom_name not in by_name
                    ]
        missing_heavy = [at for at in missing_from_input if at.element != "H"]
        if not missing_heavy and missing_from_input:
            try:
                by_index = compute_mmff94_charges(mol)
            except RuntimeError as exc:
                prefix = f"{ligand_name}: " if ligand_name else ""
                missing_names = ", ".join(at.atom_name for at in missing_from_input)
                raise RuntimeError(
                    f"{prefix}partial-charge generation failed for hydrogens "
                    f"not present in authoritative input: [{missing_names}]. "
                    f"Details: {exc}"
                ) from exc
            return {
                at.atom_name: (
                    by_name[at.atom_name]
                    if at.atom_name in by_name
                    else by_index[at.index]
                )
                for at in atom_types
            }
        if not missing_from_input:
            return {at.atom_name: by_name[at.atom_name] for at in atom_types}
    else:
        missing_from_input = list(atom_types)

    if mode == "input":
        prefix = f"{ligand_name}: " if ligand_name else ""
        missing_names = ", ".join(at.atom_name for at in missing_from_input)
        raise RuntimeError(
            f"{prefix}authoritative input charges are required (charge_mode='input') "
            f"but missing for atoms: [{missing_names}]"
        )
    try:
        by_index = compute_mmff94_charges(mol)
    except RuntimeError as exc:
        prefix = f"{ligand_name}: " if ligand_name else ""
        missing_names = ", ".join(at.atom_name for at in missing_from_input)
        raise RuntimeError(
            f"{prefix}partial-charge generation failed. "
            "No Gasteiger fallback is used; provide authoritative input "
            "charges or fix MMFF94 parameterization. "
            "For CIF inputs, load with biotite using include_bonds=True and "
            "include per-atom partial charges when available "
            "(e.g. extra_fields=['partial_charge']). "
            "Alternatively, provide pre-parameterized ligand_params_files. "
            f"Atoms requiring MMFF charges: [{missing_names}]. "
            f"Details: {exc}"
        ) from exc
    charges: dict[str, float] = {}
    for at in atom_types:
        if at.atom_name in by_name:
            charges[at.atom_name] = by_name[at.atom_name]
        elif at.index in by_index:
            charges[at.atom_name] = by_index[at.index]
    return charges
