repos:
  - repo: local
    hooks:
      - id: clang-format
        name: clang-format
        entry: clang-format -i
        language: system
        files: \.(c|cc|cpp|h|hh|cu|cuh)$
        exclude: >
            (?x)^(
                tmol/extern/.* |
                dev/.* 
            )$
  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
      - id: black
        exclude: >
            (?x)^(
                tmol/extern/.* |
                dev/.* 
                \.conda/.*
            )$
  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        exclude: >
            (?x)^(
                tmol/extern/.* |
                dev/.* 
                \.conda/.*
            )$
