repos:
  - repo: local
    hooks:
      - id: clang-format
        name: clang-format
        args: ['-i']
        description: 'Format files with ClangFormat.'
        entry: clang-format
        language: system
        files: \.(c|cc|cpp|h|hh|cu|cuh)$
        exclude: >
            (?x)^(
                tmol/extern/.* |
                dev/.* 
            )$
      - id: ruff-format
        name: ruff format
        description: 'Format Python files with ruff.'
        entry: ruff format
        language: system
        types: [python]
        exclude: >
            (?x)^(
                tmol/extern/.* |
                dev/.* 
            )$
      - id: ruff-check
        name: ruff check
        description: 'Lint Python files with ruff.'
        entry: ruff check --fix
        language: system
        types: [python]
        exclude: >
            (?x)^(
                tmol/extern/.* |
                dev/.* 
            )$
