repos:
  - repo: local
    hooks:
      - id: clang-format
        name: clang-format
        args: ['-i']
        description: 'Format files with ClangFormat.'
        entry: clang-format
        language: system
        files: \.(c|cc|cpp|h|hh|cu|cuh)$
        exclude: >
            (?x)^(
                tmol/extern/.* |
                dev/.* 
            )$
  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
      - id: black
        exclude: >
            (?x)^(
                tmol/extern/.* |
                dev/.* 
                \.conda/.*
            )$
