#!/bin/bash

set -e
set -x

# Requires an active root conda installation see:
# https://conda.io/miniconda.html
conda env update -f environment.yml
conda env update -f dev_environment.yml

set +e
pushd .git/hooks
ln -s ../../.post-checkout post-checkout
ln -s ../../.pre-commit pre-commit
popd
