"""Generate the D-amino-acid residue types by mirroring their L counterparts.

A D-amino acid is the mirror image of its L form, so it is fully determined by
that form: reflection preserves bond lengths and bond angles and negates every
dihedral. The chemistry, charges, and bonded parameters are therefore copied,
and only the signed quantities flip.

The generated residues are written to their own files, merged into the
databases at load, so regenerating them never rewrites the hand-maintained
chemical, elec, and cartbonded databases.

Run from the repository root:

    python -m tmol.support.chemical._add_d_amino_acids
"""

import argparse
import math
import os

import cattr
import yaml
from yaml import safe_load

from tmol.database.chemical import ChemicalDatabase
from tmol.database.scoring._cartbonded import CartBondedDatabase
from tmol.database.scoring._elec import ElecDatabase

# three-letter code the PDB uses for each D-amino acid; these are the codes a
#    deposited structure carries, so they drive residue-type matching on input
D_NAME3 = {
    "ALA": "DAL",
    "ARG": "DAR",
    "ASN": "DSG",
    "ASP": "DAS",
    "CYS": "DCY",
    "GLN": "DGN",
    "GLU": "DGL",
    "HIS": "DHI",
    "ILE": "DIL",
    "LEU": "DLE",
    "LYS": "DLY",
    "MET": "MED",
    "PHE": "DPN",
    "PRO": "DPR",
    "SER": "DSN",
    "THR": "DTH",
    "TRP": "DTR",
    "TYR": "DTY",
    "VAL": "DVA",
}

HEADER = (
    "# Generated by tmol.support.chemical._add_d_amino_acids -- do not edit.\n"
    "# Each entry is the mirror image of the L residue it names as its\n"
    "# reference: dihedrals are negated, everything else is copied.\n"
)


def d_name(l_name: str) -> str:
    """The name of the mirror image of an L residue type."""
    return "D" + l_name


def negate_angle(value: str) -> str:
    """Negate an angle written as a magnitude and a unit, e.g. "60.0 deg"."""
    magnitude, _, unit = str(value).partition(" ")
    return f"{-float(magnitude):.6f} {unit}"


def mirror_icoor(icoor: dict) -> dict:
    """Negate an internal coordinate's dihedral.

    Reflection preserves distances and bond angles, so ``d`` and ``theta`` are
    untouched and only the dihedral changes sign.
    """
    mirrored = dict(icoor)
    mirrored["phi"] = negate_angle(icoor["phi"])
    return mirrored


def mirror_residue(residue: dict) -> dict:
    """Build the D residue type that mirrors one L residue type."""
    l_name = residue["name"]
    out = dict(residue)
    out["name"] = d_name(l_name)
    out["base_name"] = d_name(residue["base_name"])
    out["name3"] = D_NAME3[residue["name3"]]
    out["io_equiv_class"] = D_NAME3[residue["io_equiv_class"]]
    # one-letter codes address base types, and the sequence grammar reads
    #    lowercase as DNA; a D residue is written X[DALA]
    out["one_letter_code"] = None

    out["icoors"] = [mirror_icoor(ic) for ic in residue["icoors"]]

    properties = {
        k: dict(v) if isinstance(v, dict) else v
        for k, v in residue["properties"].items()
    }
    properties["polymer"] = dict(properties["polymer"])
    properties["polymer"]["sidechain_chirality"] = "d"
    out["properties"] = properties

    # the backbone potentials are the L tables read at negated phi/psi
    out["rama_reference"] = l_name
    out["dunbrack_reference"] = residue["base_name"]
    out["reference_mirrored"] = True
    return out


def mirror_cartbonded(params: dict) -> dict:
    """Copy one residue's cartbonded parameters, negating improper phases.

    Bond lengths, angles and proper torsions are mirror-invariant. Impropers
    are the terms that hold chirality, so their phases flip.
    """
    out = {k: list(v) for k, v in params.items()}
    out["improper_parameters"] = [
        {
            key: (-value if key.startswith("phi") else value)
            for key, value in improper.items()
        }
        for improper in params.get("improper_parameters", [])
    ]
    return out


def assert_torsions_are_mirror_safe(params: dict, name: str) -> None:
    """Proper torsions must be copied verbatim, so their phases must be flat.

    A phase of 0 or pi is unchanged by negation; any other phase would make the
    torsion chirality-bearing and copying it would silently keep the L geometry.
    """
    for torsion in params.get("torsion_parameters", []):
        for i in (1, 2, 3):
            k = torsion.get(f"k{i}", 0.0)
            phi = torsion.get(f"phi{i}", 0.0)
            if k == 0.0:
                continue
            wrapped = phi % (2 * math.pi)
            offsets = (wrapped, wrapped - math.pi, wrapped - 2 * math.pi)
            if min(abs(o) for o in offsets) > 1e-6:
                raise ValueError(
                    f"{name}: proper torsion {torsion} has a chirality-bearing "
                    f"phase {phi}; it cannot be copied to the D form unchanged"
                )


def write_yaml(path: str, payload: dict) -> None:
    with open(path, "w") as outfile:
        outfile.write(HEADER)
        yaml.safe_dump(payload, outfile, default_flow_style=None, sort_keys=False)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--db_dir", default="tmol/database/default")
    args = parser.parse_args()

    chem_dir = os.path.join(args.db_dir, "chemical")
    scoring_dir = os.path.join(args.db_dir, "scoring")

    # read the hand-maintained database only, so regenerating is idempotent
    with open(os.path.join(chem_dir, "chemical.yaml"), "r") as infile:
        chemical = safe_load(infile)
    with open(os.path.join(scoring_dir, "elec.yaml"), "r") as infile:
        elec = safe_load(infile)
    with open(os.path.join(scoring_dir, "cartbonded.yaml"), "r") as infile:
        cartbonded = safe_load(infile)
    with open(os.path.join(scoring_dir, "ref.yaml"), "r") as infile:
        ref = safe_load(infile)

    sources = [
        residue
        for residue in chemical["residues"]
        if residue["name"] == residue["base_name"]
        and residue["properties"]["polymer"]["sidechain_chirality"] == "l"
    ]
    if not sources:
        raise ValueError("no chiral L residues found to mirror")

    residues, charges, cp_reps, cart, ref_weights = [], [], [], {}, {}
    for residue in sources:
        l_name = residue["name"]
        residues.append(mirror_residue(residue))
        # charges are per variant too; a c-terminus carries an OXT the base
        #    residue does not have
        charges.extend(
            {**entry, "res": d_name(entry["res"])}
            for entry in elec["atom_charge_parameters"]
            if entry["res"] == l_name or entry["res"].startswith(l_name + ":")
        )
        # countpair representatives gate which atom pairs fa_elec counts, and
        #    are keyed by residue name like the charges
        cp_reps.extend(
            {**entry, "res": d_name(entry["res"])}
            for entry in elec["atom_cp_reps_parameters"]
            if entry["res"] == l_name or entry["res"].startswith(l_name + ":")
        )
        if l_name in ref["weights"]:
            ref_weights[d_name(l_name)] = ref["weights"][l_name]
        if l_name in cartbonded["residue_params"]:
            params = cartbonded["residue_params"][l_name]
            assert_torsions_are_mirror_safe(params, l_name)
            cart[d_name(l_name)] = mirror_cartbonded(params)
        print(
            f"  {l_name:8s} -> {d_name(l_name):9s} name3 {residue['name3']} -> "
            f"{D_NAME3[residue['name3']]}"
        )

    write_yaml(os.path.join(chem_dir, "d_amino_acids.yaml"), {"residues": residues})
    write_yaml(
        os.path.join(scoring_dir, "elec_d_amino_acids.yaml"),
        {"atom_charge_parameters": charges, "atom_cp_reps_parameters": cp_reps},
    )
    write_yaml(
        os.path.join(scoring_dir, "cartbonded_d_amino_acids.yaml"),
        {"residue_params": cart},
    )
    write_yaml(
        os.path.join(scoring_dir, "ref_d_amino_acids.yaml"), {"weights": ref_weights}
    )
    print(
        f"\n{len(residues)} residues, {len(charges)} charges, "
        f"{len(cp_reps)} cp reps, {len(cart)} cartbonded, "
        f"{len(ref_weights)} ref weights"
    )

    # the databases must still load, and structure cleanly into their types
    cattr.structure(
        {**chemical, "residues": [*chemical["residues"], *residues]}, ChemicalDatabase
    )
    ElecDatabase.from_file(
        os.path.join(scoring_dir, "elec.yaml"),
        generated=[os.path.join(scoring_dir, "elec_d_amino_acids.yaml")],
    )
    CartBondedDatabase.from_file(
        os.path.join(scoring_dir, "cartbonded.yaml"),
        generated=[os.path.join(scoring_dir, "cartbonded_d_amino_acids.yaml")],
    )
    print("databases load")


if __name__ == "__main__":
    main()
