version: '2.3'
services:
  test:
    build:
      context: ..
      dockerfile: .buildkite/test/Dockerfile
    runtime: nvidia
    volumes:
      - buildkite:/buildkite
    environment:
      - BUILDKITE
      - BUILDKITE_PIPELINE_SLUG
      - BUILDKITE_AGENT_NAME
      - BUILDKITE_BRANCH
      - BUILDKITE_BUILD_NUMBER
      - BUILDKITE_JOB_ID
      - BUILDKITE_BUILD_ID
      - BUILDKITE_AGENT_ACCESS_TOKEN
      - CUDA_DEVICE_ORDER
      - CUDA_VISIBLE_DEVICES
volumes:
  buildkite:
    external: True
