version: '2.3'
services:
  test:
    build:
      context: ..
      dockerfile: .buildkite/test/Dockerfile
    runtime: nvidia
    volumes:
      - buildkite:/buildkite
    environment:
      - BUILDKITE_JOB_ID
      - BUILDKITE_BUILD_ID
      - BUILDKITE_AGENT_ACCESS_TOKEN
volumes:
  buildkite:
    external: True
