steps:
  - label: ':hammer: Build Runner'
    command: |
      docker build -f .buildkite/runner/Dockerfile . -t tmol-runner:${BUILDKITE_JOB_ID} -t tmol-runner:${BUILDKITE_COMMIT}
  - label: ':shrug: Testing'
    # Run non-linting tests in a single process, relying on internal multithreading
    command: |
      echo "--- environment"
      conda info
      conda list

      echo "--- nvidia-smi"
      nvidia-smi

      echo "--- setup"
      pip install -e .

      echo "+++ tests"

      mkdir -p report/test
      pytest -v -k 'not linting' --cov=./tmol --junitxml=report/test/test.xml 2>&1 | tee report/test/log.txt

      echo "--- report"
      buildkite-agent artifact upload "report/test/*"
    plugins:
      junit-annotate#v1.2.0:
        artifacts: report/test/test.xml
      uw-ipd/docker:
        runtime: "nvidia"
        image: "tmol-runner:${BUILDKITE_JOB_ID}"
        debug: true

  - label: ':microscope: Linting'
    command: |
      echo "+++ linting"
      pytest -n auto -k 'linting'
    plugins:
      uw-ipd/docker:
        runtime: "nvidia"
        image: "tmol-runner:${BUILDKITE_JOB_ID}"
