package:
  name: "tmol"
  version: "0.0.2"

# source:
#  git_rev: v1.0
#  git_url: https://github.com/uw-ipd/tmol/archive/refs/tags/0.0.2.tar.gz

requirements:
  build:
    - python
    - setuptools
  run:
    # core
    - python=3.7
    - pip
    - ipython
    - numpy
    - pandas
    - numba
    - scipy
    - openblas
    - libopenblas
    - requests
    - toolz
    - pyyaml
    - astor
    - zarr
    - conda-forge::pint
    - attrs
    - cattrs
    - typing_inspect
    - typish
    - frozendict
    - sparse
    # CUDA
    - pytorch=1.6
    - cudatoolkit=10.1 # [linux]
    - cudatoolkit-dev=11.4 # [linux]
    - gxx_linux-64 # [linux]
    # Test
    - pytest=3.8
    - coverage=4 # Pin, using older coverage api
    - pytest-cov
    - flake8
    - clangdev
    - virtualenv
    - psutil
    - seaborn
    - codecov
    - black
    - pre-commit
    - flake8-bugbear
    - pytest-xdist
    - pytest-faulthandler
    - pytest-benchmark
    - py3Dmol
    - hypothesis
    - itermplot
    # Dev
    - ipykernel
    - biopython
    - line_profiler
    - pytest-watch
    - pytest-instafail
    - pytest-repeat
    - pdbpp
    - ruamel.yaml
    - mamba
    - conda-lock

#about:
#  home: https://github.com/uw-ipd/tmol
#  license: MIT
#  license_file: LICENSE
#  summary: "tmol is a gpu-enabled recreation of a subset of Rosetta's functionality, intended for integration into machine learning workflows."

extra:
  recipe-maintainers:
    - fdimaio
    - aleaverfay