#!/bin/bash

set -euo pipefail

# conda setup
source /home/dimaio/.bashrc

# create env if it does not exist
if ! [ -f /home/dimaio/.conda/envs/$BUILDKITE_BUILD_ID ]; then
    conda create -n $BUILDKITE_BUILD_ID -y
    conda env update -n $BUILDKITE_BUILD_ID  --file environments/env-dev.yml --prune
fi
conda activate $BUILDKITE_BUILD_ID
