"""Protein-ligand interface scoring tests.

For each ``*_complex*.pdb`` in ``protein_ligand_test``, inject the matching
``<target>.xtal-lig.mmff94.tmol`` ligand params, score with tmol, parse the
Rosetta ``<stem>.sc`` (generated by ``run_rosetta_score.sh``), and print a
per-term comparison table (tmol vs rosetta).
"""

from pathlib import Path

import pytest
import csv
import torch

from tmol.score.score_utils import calculate_block_pair_ddg

from tmol.tests.ligand.test_dud_ligands import _load_tmol_file, _rosetta_score

PLI_DIR = Path(__file__).parent.parent / "data" / "protein_ligand_test"
PLI_CASES = sorted(p.name for p in PLI_DIR.glob("*_complex*.pdb"))


# Per-row mapping: (label, rosetta_terms, tmol_terms). Each side is summed
# and compared. The Rosetta values in score.sc are already weighted; tmol
# values are weighted via sfxn.weights_tensor() before aggregation.
_PLI_TERM_ROWS = [
    ("fa_ljatr", ("fa_atr", "fa_intra_atr_xover4"), ("fa_ljatr",)),
    ("fa_ljrep", ("fa_rep", "fa_intra_rep_xover4"), ("fa_ljrep",)),
    ("fa_lk", ("fa_sol", "fa_intra_sol_xover4"), ("fa_lk",)),
    ("fa_elec", ("fa_elec", "fa_intra_elec"), ("fa_elec",)),
    ("lk_ball_iso", ("lk_ball_iso",), ("lk_ball_iso",)),
    ("lk_ball", ("lk_ball",), ("lk_ball",)),
    ("lk_bridge", ("lk_ball_bridge",), ("lk_bridge",)),
    ("lk_bridge_uncpl", ("lk_ball_bridge_uncpl",), ("lk_bridge_uncpl",)),
    ("hbond", ("hbond_sr_bb", "hbond_lr_bb", "hbond_bb_sc", "hbond_sc"), ("hbond",)),
    ("dunbrack_rot", ("fa_dun_rot",), ("dunbrack_rot",)),
    ("dunbrack_rotdev", ("fa_dun_dev",), ("dunbrack_rotdev",)),
    ("dunbrack_semirot", ("fa_dun_semi",), ("dunbrack_semirot",)),
    ("rama", ("rama_prepro", "p_aa_pp"), ("rama",)),
    ("omega", ("omega",), ("omega",)),
    ("disulfide", ("dslf_fa13",), ("disulfide",)),
    ("ref", ("ref",), ("ref",)),
    ("gen_bonded", ("gen_bonded",), ("gen_torsions",)),
]


def _target_for_complex(pdb_name: str) -> str:
    stem = pdb_name[: -len(".pdb")]
    for suf in ("_complex_nometals", "_complex"):
        if stem.endswith(suf):
            return stem[: -len(suf)]
    return stem


class TestPLIScoring:
    """Score each protein-ligand complex and print a per-term table vs Rosetta."""

    @pytest.fixture(params=PLI_CASES)
    def pli_pdb(self, request):
        return PLI_DIR / request.param

    def test_score(self, pli_pdb, torch_device):
        import biotite.structure
        import biotite.structure.io

        from tmol.database import ParameterDatabase, inject_residue_params
        from tmol.io.pose_stack_from_biotite import pose_stack_from_biotite
        from tmol.score import beta2016_score_function

        target = _target_for_complex(pli_pdb.name)
        tmol_path = PLI_DIR / f"{target}.xtal-lig.mmff94.tmol"
        sc_path = PLI_DIR / f"{pli_pdb.stem}.sc"

        residues, partial_charges, cartbonded = _load_tmol_file(tmol_path)
        param_db = inject_residue_params(
            ParameterDatabase.get_default(),
            residue_types=residues,
            partial_charges=partial_charges,
            cartbonded_params=cartbonded,
        )

        bt_struct = biotite.structure.io.load_structure(str(pli_pdb))
        if isinstance(bt_struct, biotite.structure.AtomArrayStack):
            bt_struct = bt_struct[0]

        pose_stack = pose_stack_from_biotite(
            bt_struct, torch_device, param_db=param_db, prepare_ligands=True
        )

        sfxn = beta2016_score_function(torch_device, param_db=param_db)
        scorer = sfxn.render_whole_pose_scoring_module(pose_stack)
        unweighted = scorer.unweighted_scores(pose_stack.coords)
        weights = sfxn.weights_tensor()
        score_types = sfxn.all_score_types()
        tmol_weighted: dict[str, float] = {}
        for i, st in enumerate(score_types):
            tmol_weighted[st.name] = tmol_weighted.get(st.name, 0.0) + float(
                weights[i]
            ) * float(unweighted[i, 0])

        ros_scores = _rosetta_score(sc_path) if sc_path.exists() else {}

        tmol_total = sum(tmol_weighted.values())
        ros_total = float(ros_scores.get("total_score", 0.0))

        print(f"\n=== {pli_pdb.name}  (target={target}) ===")
        if not sc_path.exists():
            print(f"  (no Rosetta .sc at {sc_path.name} -- run run_rosetta_score.sh)")
        print(f"  {'term':<18} {'tmol':>12} {'rosetta':>12} {'diff':>12}")
        for label, ros_terms, tmol_terms in _PLI_TERM_ROWS:
            t = sum(tmol_weighted.get(n, 0.0) for n in tmol_terms)
            r = sum(float(ros_scores.get(n, 0.0)) for n in ros_terms)
            print(f"  {label:<18} {t:12.4f} {r:12.4f} {t - r:+12.4f}")
        print(
            f"  {'TOTAL':<18} {tmol_total:12.4f} {ros_total:12.4f} "
            f"{tmol_total - ros_total:+12.4f}"
        )

    def test_compare_dg_score_with_rosetta(self, pli_pdb, torch_device):
        import biotite.structure
        import biotite.structure.io
        import biotite.structure.io.pdbx as pdbx

        from tmol.database import ParameterDatabase, inject_residue_params
        from tmol.io.pose_stack_from_biotite import pose_stack_from_biotite
        from tmol.ligand import prepare_ligands
        from tmol.score import beta2016_score_function

        target = _target_for_complex(pli_pdb.name)
        tmol_path = PLI_DIR / f"{target}.xtal-lig.mmff94.tmol"
        sc_path = PLI_DIR / f"{pli_pdb.stem}.sc"
        ligand_cif = PLI_DIR / "cif_inputs" / f"{target}.ligand.cif"

        # if target in ["ace","ada"]:
        # return

        residues, partial_charges, cartbonded = _load_tmol_file(tmol_path)
        param_db = inject_residue_params(
            ParameterDatabase.get_default(),
            residue_types=residues,
            partial_charges=partial_charges,
            cartbonded_params=cartbonded,
        )

        ligand_pdbx = pdbx.CIFFile.read(str(ligand_cif))
        bt_ligand = pdbx.get_structure(
            ligand_pdbx, model=1, include_bonds=True, extra_fields=["charge"]
        )
        extended_db, _ = prepare_ligands(bt_ligand)

        bt_struct = biotite.structure.io.load_structure(str(pli_pdb))
        if isinstance(bt_struct, biotite.structure.AtomArrayStack):
            bt_struct = bt_struct[0]

        pose_stack_converted = pose_stack_from_biotite(
            bt_struct, torch_device, param_db=param_db
        )
        pose_stack_generated = pose_stack_from_biotite(
            bt_struct, torch_device, param_db=extended_db
        )

        sfxn = beta2016_score_function(torch_device, param_db=param_db)
        score_types = sfxn.all_score_types()

        mask = torch.zeros(
            (1, pose_stack_converted.max_n_blocks),
            dtype=torch.bool,
            device=torch_device,
        )
        mask[0][-1] = True

        # Parameterized: run calculate_block_pair_ddg for each (label, pose_stack, minimize)
        # and directly encode the per-term dictionaries.
        _configs = [
            ("converted", pose_stack_converted, False),
            ("generated", pose_stack_generated, False),
            ("converted_minimized", pose_stack_converted, True),
            ("generated_minimized", pose_stack_generated, True),
        ]
        ddg_results = {}
        for label, pstack, do_minimize in _configs:
            print("Calculating dg for", label)
            raw = calculate_block_pair_ddg(
                pstack, mask, sum_terms=False, minimize=do_minimize
            )
            ddg_results[label] = {
                key.name: val.item() for key, val in zip(score_types, raw.squeeze(0))
            }

        ros_scores = _rosetta_score(sc_path) if sc_path.exists() else {}

        data = []
        print(f"\n=== {pli_pdb.name}  (target={target}) ===")
        if not sc_path.exists():
            print(f"  (no Rosetta .sc at {sc_path.name} -- run run_rosetta_score.sh)")
        print(f"  {'term':<18} {'tmol':>12} {'rosetta':>12} {'diff':>12}")
        for label, ros_terms, tmol_terms in _PLI_TERM_ROWS:
            converted = sum(ddg_results["converted"].get(n, 0.0) for n in tmol_terms)
            generated = sum(ddg_results["generated"].get(n, 0.0) for n in tmol_terms)
            converted_min = sum(
                ddg_results["converted_minimized"].get(n, 0.0) for n in tmol_terms
            )
            generated_min = sum(
                ddg_results["generated_minimized"].get(n, 0.0) for n in tmol_terms
            )
            # rosetta = sum(float(ros_scores.get(n, 0.0)) for n in ros_terms)
            rosetta = sum(float(ros_scores.get("dG_" + n, 0.0)) for n in ros_terms)
            data += [
                (
                    target,
                    ",".join(tmol_terms),
                    ",".join(ros_terms),
                    converted,
                    generated,
                    converted_min,
                    generated_min,
                    rosetta,
                    abs(converted - rosetta),
                    abs(generated - generated_min),
                )
            ]
            print(
                f"  {label:<18} {converted:12.4f} {generated:12.4f} {rosetta:12.4f} {converted - rosetta:+12.4f}"
            )

        with open(target + ".table", "w") as f:
            writer = csv.writer(
                f, delimiter=" ", quotechar="|", quoting=csv.QUOTE_MINIMAL
            )
            for row in data:
                writer.writerow(row)
