"""Tests for the non-destructive mol2 -> tmol params entry point.

Validates that ``prepare_ligand_from_mol2`` reads a mol2 verbatim:
atom names, 3D coordinates, partial charges, and bond orders all flow
through without regeneration. Also covers the ``rename_atoms`` flag and
end-to-end comparison against Rosetta's ``mol2genparams.py`` output.

The Rosetta reference files (``rosetta_ref1.params``, ``rosetta_ref2.params``)
were generated by running
``mol2genparams.py -s ref{1,2}.mol2`` on the matching ``.mol2`` test data,
so they reflect Rosetta's default behavior (preserve mol2 atom names).
"""

from pathlib import Path

import pytest

from tmol.ligand.mol2_io import (
    atom_array_from_mol2,
    parse_mol2_atom_names,
    prepare_ligand_from_mol2,
    read_mol2,
    write_params_from_mol2,
)
from tmol.ligand.params_io import read_params_file


GROUND_TRUTH_DIR = Path(__file__).parent.parent / "data" / "ligand_ground_truth"
REF1_MOL2 = GROUND_TRUTH_DIR / "ref1.mol2"
REF2_MOL2 = GROUND_TRUTH_DIR / "ref2.mol2"
ROSETTA_REF1_PARAMS = GROUND_TRUTH_DIR / "rosetta_ref1.params"
ROSETTA_REF2_PARAMS = GROUND_TRUTH_DIR / "rosetta_ref2.params"


def _parse_mol2_atom_block(path: Path) -> list[dict]:
    """Return one dict per TRIPOS ATOM row with name, xyz, charge."""
    rows: list[dict] = []
    in_atom = False
    with open(path) as fh:
        for line in fh:
            stripped = line.strip()
            if stripped.startswith("@<TRIPOS>"):
                in_atom = stripped == "@<TRIPOS>ATOM"
                continue
            if not in_atom or not stripped:
                continue
            cols = stripped.split()
            if len(cols) < 9:
                continue
            rows.append(
                {
                    "name": cols[1],
                    "xyz": (float(cols[2]), float(cols[3]), float(cols[4])),
                    "sybyl": cols[5],
                    "charge": float(cols[8]),
                }
            )
    return rows


def _params_atom_lines(path: Path) -> list[tuple[str, str, float]]:
    """Return [(name, atom_type, charge), ...] from ATOM lines in a params file."""
    out: list[tuple[str, str, float]] = []
    with open(path) as fh:
        for line in fh:
            cols = line.split()
            if cols and cols[0] == "ATOM" and len(cols) >= 5:
                out.append((cols[1], cols[2], float(cols[4])))
    return out


def _params_bond_set(path: Path) -> set[frozenset]:
    """Return the set of {a, b} undirected pairs from BOND/BOND_TYPE lines."""
    out: set[frozenset] = set()
    with open(path) as fh:
        for line in fh:
            cols = line.split()
            if cols and cols[0] in ("BOND", "BOND_TYPE") and len(cols) >= 3:
                out.add(frozenset((cols[1], cols[2])))
    return out


# ---------------------------------------------------------------------------
# Module-level smoke tests
# ---------------------------------------------------------------------------


def test_read_mol2_returns_first_molecule():
    mol = read_mol2(REF1_MOL2)
    assert mol.OBMol.NumAtoms() == 51


def test_read_mol2_missing_path():
    with pytest.raises(FileNotFoundError):
        read_mol2(REF1_MOL2.parent / "does_not_exist.mol2")


def test_parse_mol2_atom_names_matches_atom_block():
    parsed = parse_mol2_atom_names(REF1_MOL2)
    expected = [row["name"] for row in _parse_mol2_atom_block(REF1_MOL2)]
    assert parsed == expected
    assert len(parsed) == 51


# ---------------------------------------------------------------------------
# Atom-name preservation / regeneration
# ---------------------------------------------------------------------------


def test_atom_names_preserved_by_default():
    """Default rename_atoms=False: all heavy + H names match the mol2 column."""
    restype, _ = prepare_ligand_from_mol2(REF1_MOL2, res_name="LG1")
    mol2_names = [row["name"] for row in _parse_mol2_atom_block(REF1_MOL2)]
    assert [a.name for a in restype.atoms] == mol2_names


def test_atom_names_regenerated_with_flag():
    """rename_atoms=True: H names follow H<bonded_element><count> convention."""
    restype, _ = prepare_ligand_from_mol2(
        REF1_MOL2, res_name="LG1", rename_atoms=True
    )
    names = [a.name for a in restype.atoms]
    # Heavy atoms in ref1.mol2 already use <elem><n> convention, so they
    # are unchanged; only H names should differ (H1->HC1/HO1/HN1/HR1).
    h_names = [n for n in names if n.startswith("H")]
    assert h_names, "expected hydrogens in the residue"
    for n in h_names:
        assert len(n) >= 3 and n[1].isalpha(), (
            f"H name {n!r} should follow H<elem><n> convention "
            "under rename_atoms=True"
        )
    mol2_h_names = {
        row["name"]
        for row in _parse_mol2_atom_block(REF1_MOL2)
        if row["name"].startswith("H")
    }
    assert set(h_names) != mol2_h_names, "H names should differ from the mol2 names"


def test_atom_count_matches_mol2():
    restype, _ = prepare_ligand_from_mol2(REF1_MOL2, res_name="LG1")
    assert len(restype.atoms) == 51


# ---------------------------------------------------------------------------
# Charges & coordinates pass through verbatim
# ---------------------------------------------------------------------------


def test_charges_preserved_from_mol2_default_names():
    """Returned charges equal the mol2 column-9 values."""
    _, charges = prepare_ligand_from_mol2(REF1_MOL2, res_name="LG1")
    mol2_rows = _parse_mol2_atom_block(REF1_MOL2)
    for row in mol2_rows:
        assert row["name"] in charges, f"missing charge for {row['name']}"
        assert abs(charges[row["name"]] - row["charge"]) < 1e-4, (
            f"charge for {row['name']}: got {charges[row['name']]}, "
            f"expected {row['charge']}"
        )


def test_coordinates_preserved_in_read():
    """OBMol coords from read_mol2 equal mol2 column 3-5 verbatim."""
    mol = read_mol2(REF1_MOL2)
    mol2_xyzs = [row["xyz"] for row in _parse_mol2_atom_block(REF1_MOL2)]
    from openbabel import openbabel

    for i, obatom in enumerate(openbabel.OBMolAtomIter(mol.OBMol)):
        x, y, z = obatom.GetX(), obatom.GetY(), obatom.GetZ()
        ex, ey, ez = mol2_xyzs[i]
        assert abs(x - ex) < 1e-6 and abs(y - ey) < 1e-6 and abs(z - ez) < 1e-6, (
            f"coord mismatch at atom {i}: got ({x}, {y}, {z}), "
            f"expected ({ex}, {ey}, {ez})"
        )


# ---------------------------------------------------------------------------
# Confirm the destructive steps are skipped
# ---------------------------------------------------------------------------


def test_no_dimorphite_invoked(monkeypatch):
    """The mol2 path must not call dimorphite_dl protonation."""
    import tmol.ligand.dimorphite_dl as dd

    def _boom(*args, **kwargs):
        raise AssertionError("dimorphite_dl must not be called on the mol2 path")

    monkeypatch.setattr(dd, "protonate_mol_variants", _boom)
    restype, _ = prepare_ligand_from_mol2(REF1_MOL2, res_name="LG1")
    assert len(restype.atoms) == 51


def test_no_mmff94_charge_recompute(monkeypatch):
    """The mol2 path must not invoke OBChargeModel to recompute charges."""
    from openbabel import openbabel

    original_find_type = openbabel.OBChargeModel.FindType

    def _boom(name):
        raise AssertionError(
            "OBChargeModel.FindType must not be called on the mol2 path "
            f"(tried to load {name!r})"
        )

    monkeypatch.setattr(openbabel.OBChargeModel, "FindType", staticmethod(_boom))
    try:
        _, charges = prepare_ligand_from_mol2(REF1_MOL2, res_name="LG1")
    finally:
        monkeypatch.setattr(
            openbabel.OBChargeModel, "FindType", staticmethod(original_find_type)
        )
    mol2_rows = _parse_mol2_atom_block(REF1_MOL2)
    for row in mol2_rows:
        assert abs(charges[row["name"]] - row["charge"]) < 1e-4


# ---------------------------------------------------------------------------
# End-to-end comparison against Rosetta mol2genparams.py output
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "mol2_path, rosetta_params_path, res_name",
    [
        (REF1_MOL2, ROSETTA_REF1_PARAMS, "LG1"),
        (REF2_MOL2, ROSETTA_REF2_PARAMS, "LG1"),
    ],
    ids=["ref1", "ref2"],
)
def test_atom_names_match_rosetta(mol2_path, rosetta_params_path, res_name):
    """Atom names emitted by the tmol mol2 path equal Rosetta's atom names."""
    restype, _ = prepare_ligand_from_mol2(mol2_path, res_name=res_name)
    actual = [a.name for a in restype.atoms]
    expected = [n for n, _, _ in _params_atom_lines(rosetta_params_path)]
    assert actual == expected


@pytest.mark.parametrize(
    "mol2_path, rosetta_params_path, res_name",
    [
        (REF1_MOL2, ROSETTA_REF1_PARAMS, "LG1"),
        (REF2_MOL2, ROSETTA_REF2_PARAMS, "LG1"),
    ],
    ids=["ref1", "ref2"],
)
def test_atom_types_match_rosetta(mol2_path, rosetta_params_path, res_name):
    """tmol's atom-type classifier output matches Rosetta's per-atom types."""
    restype, _ = prepare_ligand_from_mol2(mol2_path, res_name=res_name)
    actual = [(a.name, a.atom_type) for a in restype.atoms]
    expected = [(n, t) for n, t, _ in _params_atom_lines(rosetta_params_path)]
    assert actual == expected


@pytest.mark.parametrize(
    "mol2_path, rosetta_params_path, res_name",
    [
        (REF1_MOL2, ROSETTA_REF1_PARAMS, "LG1"),
        (REF2_MOL2, ROSETTA_REF2_PARAMS, "LG1"),
    ],
    ids=["ref1", "ref2"],
)
def test_charges_match_rosetta(mol2_path, rosetta_params_path, res_name):
    """Per-atom charges match Rosetta's params (which preserves mol2 charges)."""
    _, charges = prepare_ligand_from_mol2(mol2_path, res_name=res_name)
    expected = {n: q for n, _, q in _params_atom_lines(rosetta_params_path)}
    for name, q in expected.items():
        assert name in charges, f"missing charge for {name}"
        assert abs(charges[name] - q) < 1e-3, (
            f"charge for {name}: got {charges[name]}, expected {q}"
        )


@pytest.mark.parametrize(
    "mol2_path, rosetta_params_path, res_name",
    [
        (REF1_MOL2, ROSETTA_REF1_PARAMS, "LG1"),
        (REF2_MOL2, ROSETTA_REF2_PARAMS, "LG1"),
    ],
    ids=["ref1", "ref2"],
)
def test_bond_set_matches_rosetta(mol2_path, rosetta_params_path, res_name):
    """Bond connectivity (undirected pairs) matches Rosetta's params."""
    restype, _ = prepare_ligand_from_mol2(mol2_path, res_name=res_name)
    actual = {frozenset((a, b)) for a, b, _ in restype.bonds}
    expected = _params_bond_set(rosetta_params_path)
    assert actual == expected


# ---------------------------------------------------------------------------
# atom_array_from_mol2 helper (route to pose_stack_from_biotite)
# ---------------------------------------------------------------------------


def test_atom_array_from_mol2_atom_count():
    arr = atom_array_from_mol2(REF1_MOL2, res_name="LG1")
    assert len(arr) == 51


def test_atom_array_from_mol2_names_match_mol2():
    arr = atom_array_from_mol2(REF1_MOL2, res_name="LG1")
    mol2_names = [row["name"] for row in _parse_mol2_atom_block(REF1_MOL2)]
    assert list(arr.atom_name) == mol2_names


def test_atom_array_from_mol2_names_match_restype():
    """AtomArray names must equal RawResidueType names so pose-stack can lookup."""
    arr = atom_array_from_mol2(REF1_MOL2, res_name="LG1")
    restype, _ = prepare_ligand_from_mol2(REF1_MOL2, res_name="LG1")
    assert list(arr.atom_name) == [a.name for a in restype.atoms]


def test_atom_array_from_mol2_coords_match_mol2():
    import numpy as np

    arr = atom_array_from_mol2(REF1_MOL2, res_name="LG1")
    mol2_xyzs = np.array(
        [row["xyz"] for row in _parse_mol2_atom_block(REF1_MOL2)], dtype=np.float32
    )
    assert np.allclose(arr.coord, mol2_xyzs, atol=1e-5)


def test_atom_array_from_mol2_annotations():
    arr = atom_array_from_mol2(REF1_MOL2, res_name="LG1", chain_id="L", res_id=999)
    assert set(arr.res_name) == {"LG1"}
    assert set(arr.chain_id) == {"L"}
    assert set(arr.res_id.tolist()) == {999}
    assert all(arr.hetero)


def test_atom_array_from_mol2_has_bonds():
    arr = atom_array_from_mol2(REF1_MOL2, res_name="LG1")
    assert arr.bonds is not None
    assert arr.bonds.get_bond_count() == 55  # ref1.mol2 declares 55 bonds


def test_atom_array_from_mol2_rename_atoms_aligns_with_restype():
    """With rename_atoms=True on both sides, names still align."""
    arr = atom_array_from_mol2(REF1_MOL2, res_name="LG1", rename_atoms=True)
    restype, _ = prepare_ligand_from_mol2(
        REF1_MOL2, res_name="LG1", rename_atoms=True
    )
    assert list(arr.atom_name) == [a.name for a in restype.atoms]


def test_write_params_from_mol2_round_trip(tmp_path):
    """write_params_from_mol2 -> read_params_file preserves atoms and bonds."""
    out = tmp_path / "ref1_out.params"
    write_params_from_mol2(REF1_MOL2, out, res_name="LG1")
    restype = read_params_file(out)

    expected_atoms = [(n, t) for n, t, _ in _params_atom_lines(ROSETTA_REF1_PARAMS)]
    actual_atoms = [(a.name, a.atom_type) for a in restype.atoms]
    assert actual_atoms == expected_atoms

    expected_bonds = _params_bond_set(ROSETTA_REF1_PARAMS)
    actual_bonds = {frozenset((a, b)) for a, b, _ in restype.bonds}
    assert actual_bonds == expected_bonds
