from typing import Dict, Tuple

from tmol.database._yaml import safe_load
import attr
import cattr


@attr.s(auto_attribs=True, slots=True, frozen=True)
class NaTorsionGlobalParams:
    sdev_sugar: float
    sdev_chi: float
    sdev_backbone: Tuple[float, ...]  # alpha beta gamma delta epsilon zeta
    weight_bb: float
    weight_chi: float
    weight_sugar: float
    pucker_temperature: float
    bin_blend_sdev: float


@attr.s(auto_attribs=True, slots=True, frozen=True)
class NaTorsionWells:
    """Bin-population energies, -ln P shifted so the deepest well is 0."""

    pucker: Tuple[float, ...]
    alpha_gamma: Tuple[Tuple[float, ...], ...]
    bibii_given_pucker: Tuple[Tuple[float, ...], ...]
    alphanext_given_bibii: Tuple[Tuple[float, ...], ...]
    chi_syn_given_pucker: dict[str, dict[str, Tuple[float, ...]]]


@attr.s(auto_attribs=True, slots=True, frozen=True)
class NaTorsionDatabase:
    """Mean nucleic acid torsion angles by bin, one parameter set per polymer.

    Generated by tmol/support/scoring/na_torsion_param_import.py. Every field is
    keyed "dna" or "rna" first; the functional form is shared, the numbers are
    not. Backbone means are then keyed by torsion name (3 bins for alpha/gamma,
    2 for the rest); sugar means by torsion name then "all", except chi which is
    per base -- acgt for DNA, acgu for RNA.
    """

    global_parameters: Dict[str, NaTorsionGlobalParams]
    backbone_means: Dict[str, Dict[str, Tuple[float, ...]]]
    sugar_means: Dict[str, Dict[str, Dict[str, Tuple[float, ...]]]]
    well_energies: Dict[str, NaTorsionWells]

    @classmethod
    def from_file(cls, path):
        with open(path, "r") as infile:
            raw = safe_load(infile)
        return cattr.structure(raw, cls)
