from typing import Tuple

import yaml
import attr
import cattr


@attr.s(auto_attribs=True, slots=True, frozen=True)
class DnaDihedralGlobalParams:
    sdev_sugar: float
    sdev_chi: float
    sdev_backbone: Tuple[float, ...]  # alpha beta gamma delta epsilon zeta
    weight_bb: float
    weight_chi: float
    weight_sugar: float
    pucker_temperature: float
    bin_blend_sdev: float


@attr.s(auto_attribs=True, slots=True, frozen=True)
class DnaDihedralWells:
    """Bin-population energies, -ln P shifted so the deepest well is 0."""

    pucker: Tuple[float, ...]
    alpha_gamma: Tuple[Tuple[float, ...], ...]
    bibii_given_pucker: Tuple[Tuple[float, ...], ...]
    alphanext_given_bibii: Tuple[Tuple[float, ...], ...]
    chi_syn_given_pucker: dict[str, dict[str, Tuple[float, ...]]]


@attr.s(auto_attribs=True, slots=True, frozen=True)
class DnaDihedralDatabase:
    """Mean DNA torsion angles by bin.

    Generated by tmol/support/scoring/dna_dihedral_param_import.py. Backbone
    means are keyed by torsion name (3 bins for alpha/gamma, 2 for the rest);
    sugar means by torsion name then "all", except chi which is per base.
    """

    global_parameters: DnaDihedralGlobalParams
    backbone_means: dict[str, Tuple[float, ...]]
    sugar_means: dict[str, dict[str, Tuple[float, ...]]]
    well_energies: DnaDihedralWells

    @classmethod
    def from_file(cls, path):
        with open(path, "r") as infile:
            raw = yaml.safe_load(infile)
        return cattr.structure(raw, cls)
